<?php
/**
 * Plugin bootstrap and hook wiring.
 *
 * @package SimpleX402
 */

declare(strict_types=1);

namespace SimpleX402;

use SimpleX402\Admin\PaywallIndicator;
use SimpleX402\Admin\SettingsPage;
use SimpleX402\Admin\TestConnectionAjax;
use SimpleX402\Connectors\ConnectorRegistry;
use SimpleX402\Connectors\TestConnectorRegistrar;
use SimpleX402\Facilitator\FacilitatorResolver;
use SimpleX402\Http\PaywallController;
use SimpleX402\Services\AllPostsModeNoticeEmitter;
use SimpleX402\Services\BotDetector;
use SimpleX402\Services\CategoryRepository;
use SimpleX402\Services\DefaultPaywallRule;
use SimpleX402\Services\GrantStore;
use SimpleX402\Services\PaywallCategoryGuard;
use SimpleX402\Services\RuleResolver;
use SimpleX402\Services\SettingsChangeNotifier;
use SimpleX402\Settings\SettingsRepository;

/**
 * Wires services to WordPress hooks.
 *
 * This is the only class that touches WordPress globals or side-effectful
 * functions like add_action / exit. Everything else is a testable,
 * dependency-injected plain PHP class.
 */
final class Plugin {

	/**
	 * Bootstrap the plugin. Idempotent — safe to call at most once per request.
	 */
	public static function boot(): void {
		$notifier     = new SettingsChangeNotifier();
		$settings     = new SettingsRepository();
		$rules        = new RuleResolver();
		$connectors   = new ConnectorRegistry();
		$resolver     = new FacilitatorResolver( $connectors );
		$controller   = new PaywallController(
			$rules,
			new GrantStore(),
			$settings,
			$resolver,
		);
		$bots         = new BotDetector( self::current_user_agent() );
		$default_rule = new DefaultPaywallRule( $settings, $bots );
		$categories   = new CategoryRepository();
		$guard        = new PaywallCategoryGuard( $settings, $categories, $notifier );
		$mode_note    = new AllPostsModeNoticeEmitter( $notifier );
		$indicator    = new PaywallIndicator( $rules );

		add_filter( RuleResolver::HOOK, $default_rule, 10, 2 );

		$indicator->register();

		add_action(
			'update_option_' . SettingsRepository::OPTION_NAME,
			$mode_note,
			10,
			2
		);

		// Heal the setting when the stored paywall category is deleted from
		// outside the plugin (e.g. via the Categories admin screen). Without
		// this, the paywall silently disables itself.
		add_action( 'delete_term', $guard, 10, 4 );

		$test_connector = new TestConnectorRegistrar();
		add_action( 'wp_connectors_init', $test_connector );
		add_filter(
			'simple_x402_facilitator_for_connector',
			array( $test_connector, 'provide_facilitator' ),
			10,
			2
		);

		if ( is_admin() ) {
			( new SettingsPage( $settings, $connectors ) )->register();
			( new TestConnectionAjax( $resolver ) )->register();
		}

		add_action(
			'template_redirect',
			static function () use ( $controller ): void {
				$post_id = is_singular() ? (int) get_queried_object_id() : 0;
				$path    = (string) ( wp_parse_url(
					home_url( add_query_arg( array() ) ),
					PHP_URL_PATH
				) ?? '/' );
				$method  = isset( $_SERVER['REQUEST_METHOD'] )
					? sanitize_text_field( (string) wp_unslash( $_SERVER['REQUEST_METHOD'] ) )
					: 'GET';

				$controller->handle(
					array(
						'path'     => $path,
						'method'   => $method,
						'post_id'  => $post_id,
						'singular' => is_singular(),
						'headers'  => self::collect_headers(),
					)
				);

				if ( ! empty( $GLOBALS['__sx402_response']['exited'] ) ) {
					foreach ( $GLOBALS['__sx402_response']['headers'] as $name => $value ) {
						header( $name . ': ' . $value );
					}
					echo (string) $GLOBALS['__sx402_response']['body']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON body generated by wp_json_encode.
					exit;
				}
			}
		);
	}

	/**
	 * Activation hook: ensure the default paywall category exists and that
	 * the stored setting binds to it (idempotent — preserves any existing
	 * admin-chosen binding across reactivations).
	 */
	public static function activate(): void {
		$categories = new CategoryRepository();
		$default_id = $categories->ensure_default_term_id();

		$settings = new SettingsRepository();
		if ( $settings->paywall_category_term_id() <= 0 ) {
			$settings->set_paywall_category_term_id( $default_id );
		}
	}

	/**
	 * HTTP User-Agent for this request, unslashed (WordPress convention).
	 */
	private static function current_user_agent(): string {
		return isset( $_SERVER['HTTP_USER_AGENT'] )
			? (string) wp_unslash( $_SERVER['HTTP_USER_AGENT'] )
			: '';
	}

	/**
	 * Collect inbound HTTP headers from $_SERVER.
	 *
	 * @return array<string,string>
	 */
	private static function collect_headers(): array {
		$out = array();
		foreach ( $_SERVER as $key => $value ) {
			if ( str_starts_with( (string) $key, 'HTTP_' ) ) {
				$name         = str_replace( '_', '-', substr( (string) $key, 5 ) );
				$out[ $name ] = sanitize_text_field( (string) wp_unslash( $value ) );
			}
		}
		return $out;
	}
}
