<?php
/**
 * Plugin bootstrap and hook wiring.
 *
 * @package SimpleX402
 */

declare(strict_types=1);

namespace SimpleX402;

use SimpleX402\Http\PaywallController;
use SimpleX402\Services\DefaultPaywallRule;
use SimpleX402\Services\GrantStore;
use SimpleX402\Services\PaymentRequirementsBuilder;
use SimpleX402\Services\RuleResolver;
use SimpleX402\Services\X402FacilitatorClient;
use SimpleX402\Settings\SettingsRepository;

/**
 * Wires services to WordPress hooks.
 *
 * This is the only class that touches WordPress globals or side-effectful
 * functions like add_action / exit. Everything else is a testable,
 * dependency-injected plain PHP class.
 */
final class Plugin {

	/**
	 * Bootstrap the plugin. Idempotent — safe to call at most once per request.
	 */
	public static function boot(): void {
		$settings     = new SettingsRepository();
		$controller   = new PaywallController(
			new RuleResolver(),
			new PaymentRequirementsBuilder(),
			new X402FacilitatorClient(),
			new GrantStore(),
			$settings
		);
		$default_rule = new DefaultPaywallRule( $settings );

		add_filter( RuleResolver::HOOK, $default_rule, 10, 2 );

		add_action(
			'template_redirect',
			static function () use ( $controller ): void {
				$post_id = is_singular() ? (int) get_queried_object_id() : 0;
				$path    = (string) ( wp_parse_url(
					home_url( add_query_arg( array() ) ),
					PHP_URL_PATH
				) ?? '/' );
				$method  = isset( $_SERVER['REQUEST_METHOD'] )
					? sanitize_text_field( (string) wp_unslash( $_SERVER['REQUEST_METHOD'] ) )
					: 'GET';

				$controller->handle(
					array(
						'path'    => $path,
						'method'  => $method,
						'post_id' => $post_id,
						'headers' => self::collect_headers(),
					)
				);

				if ( ! empty( $GLOBALS['__sx402_response']['exited'] ) ) {
					foreach ( $GLOBALS['__sx402_response']['headers'] as $name => $value ) {
						header( $name . ': ' . $value );
					}
					echo (string) $GLOBALS['__sx402_response']['body']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON body generated by wp_json_encode.
					exit;
				}
			}
		);
	}

	/**
	 * Activation hook: ensure the `paywall` tag and category exist.
	 */
	public static function activate(): void {
		foreach ( array( 'post_tag', 'category' ) as $taxonomy ) {
			if ( ! term_exists( DefaultPaywallRule::TERM, $taxonomy ) ) {
				wp_insert_term( DefaultPaywallRule::TERM, $taxonomy );
			}
		}
	}

	/**
	 * Collect inbound HTTP headers from $_SERVER.
	 *
	 * @return array<string,string>
	 */
	private static function collect_headers(): array {
		$out = array();
		foreach ( $_SERVER as $key => $value ) {
			if ( str_starts_with( (string) $key, 'HTTP_' ) ) {
				$name         = str_replace( '_', '-', substr( (string) $key, 5 ) );
				$out[ $name ] = sanitize_text_field( (string) wp_unslash( $value ) );
			}
		}
		return $out;
	}
}
